### ISSUE TITLE
Feedstock build failed

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/uiautomation-feedstock#4]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@ocefpaf - Could you please take a look and help or point me in the right direction

Staged Recipe that passed windows build
https://github.com/conda-forge/staged-recipes/pull/24010
FeedStock
https://github.com/conda-forge/uiautomation-feedstock/runs/16937075532
Failure while building
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=783813&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3

```
Processing $SRC_DIR
  Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-vu0cy_9x'
  Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
  Created temporary directory: /tmp/pip-pip-egg-info-z6ds1d20
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/feedstock_root/build_artifacts/uiautomation_1695146887178/work/setup.py", line 4, in <module>
      from uiautomation import VERSION, AUTHOR_MAIL
    File "/home/conda/feedstock_root/build_artifacts/uiautomation_1695146887178/work/uiautomation/__init__.py", line 4, in <module>
      from .uiautomation import *
    File "/home/conda/feedstock_root/build_artifacts/uiautomation_1695146887178/work/uiautomation/uiautomation.py", line 23, in <module>
      import comtypes  # need 'pip install comtypes'
      ^^^^^^^^^^^^^^^
  ModuleNotFoundError: No module named 'comtypes'
  error: subprocess-exited-with-error

```

### Installed packages

```shell
Feedstock
```

### Environment info

```shell
Feedstock
```

**Comment by ocefpaf** [comment]
A rerender should work.

@conda-forge-admin, please rerender
